services:

  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn runewell.wsgi:application --bind 0.0.0.0:8000"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG_MODE: ${DEBUG_MODE}
    volumes:
      - static_volume:/app/staticfiles
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  static_volume: